# Generated by Django 3.1.2 on 2020-11-01 22:14

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ("que", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuthorizedTeamsUser",
            fields=[
                (
                    "id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("principal_name", models.CharField(max_length=100)),
                (
                    "display_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("title", models.CharField(blank=True, max_length=100, null=True)),
                ("token", jsonfield.fields.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(name="Person",),
    ]
