# Generated by Django 3.1.2 on 2020-11-02 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('que', '0003_auto_20201102_0919'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='queueticket',
            options={'ordering': ['in_queue_since']},
        ),
    ]
