# Generated by Django 3.1.3 on 2020-11-02 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('que', '0005_principalname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queueticket',
            name='in_queue_since',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
