# Generated by Django 3.1.3 on 2020-11-03 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('que', '0007_pastmeeting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pastmeeting',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
