# Generated by Django 3.1.3 on 2020-11-03 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("que", "0008_auto_20201103_0805"),
    ]

    operations = [
        migrations.AlterField(
            model_name="queueticket",
            name="in_queue_since",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
