# Generated by Django 3.1.3 on 2020-11-05 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('que', '0009_auto_20201103_0829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queueticket',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='que.authorizedteamsuser', unique=True),
        ),
    ]
